spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/grouptravel?serverTimezone=UTC
    username: root
    data-password: 123456
  #禁用模板引擎的缓存
  thymeleaf:
    cache: false
#    实现thymleaf的页面跳转
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
logging:
  level:
    hust: debug


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: hust.shixun.grouptravel.entities

web:
  upload-path: /Users/yimmerse/upload